-- ============================================================
-- TableFlow — Initial Schema
-- Milestone 1: All core tables with tenant isolation
-- Every table (except restaurants) has restaurant_id FK
-- ============================================================

-- gen_random_uuid() is built into PostgreSQL 13+ — no extension needed

-- ============================================================
-- 1. restaurants (tenant table)
-- ============================================================
CREATE TABLE restaurants (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug        TEXT UNIQUE NOT NULL,
  name        TEXT NOT NULL,
  logo_url    TEXT,
  brand_color TEXT,
  currency    TEXT NOT NULL DEFAULT 'INR',
  timezone    TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE restaurants IS 'Tenant table — one row per onboarded restaurant';
COMMENT ON COLUMN restaurants.slug IS 'URL-safe identifier used in routing: /[slug]/...';

-- ============================================================
-- 2. tables (physical restaurant tables)
-- ============================================================
CREATE TABLE tables (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  label         TEXT NOT NULL,
  qr_code_url   TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE tables IS 'Physical tables within a restaurant';
COMMENT ON COLUMN tables.label IS 'Human-readable label, e.g. "Table 4", "Patio 2"';

-- Index for tenant-scoped queries
CREATE INDEX idx_tables_restaurant ON tables(restaurant_id);

-- ============================================================
-- 3. table_sessions (one active session per table at a time)
-- ============================================================
CREATE TABLE table_sessions (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  table_id      UUID NOT NULL REFERENCES tables(id) ON DELETE CASCADE,
  otp           CHAR(4) NOT NULL,
  otp_attempts  INT NOT NULL DEFAULT 0,
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  opened_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  closed_at     TIMESTAMPTZ
);

COMMENT ON TABLE table_sessions IS 'Waiter opens a session when seating customers; one active session per table';
COMMENT ON COLUMN table_sessions.otp IS '4-digit code generated by waiter for customers to join';
COMMENT ON COLUMN table_sessions.otp_attempts IS 'Tracks failed OTP entries for rate limiting (max 5)';

-- Indexes for common queries
CREATE INDEX idx_sessions_restaurant ON table_sessions(restaurant_id);
CREATE INDEX idx_sessions_table ON table_sessions(table_id);
CREATE INDEX idx_sessions_status ON table_sessions(status) WHERE status = 'active';

-- Ensure only one active session per table at a time
CREATE UNIQUE INDEX idx_one_active_session_per_table
  ON table_sessions(table_id)
  WHERE status = 'active';

-- ============================================================
-- 4. menu_categories
-- ============================================================
CREATE TABLE menu_categories (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  display_order INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE menu_categories IS 'Menu sections like Mains, Drinks, Desserts';

CREATE INDEX idx_menu_categories_restaurant ON menu_categories(restaurant_id);

-- ============================================================
-- 5. menu_items
-- ============================================================
CREATE TABLE menu_items (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  category_id   UUID NOT NULL REFERENCES menu_categories(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  description   TEXT,
  price         NUMERIC NOT NULL CHECK (price >= 0),
  image_url     TEXT,
  is_available  BOOLEAN NOT NULL DEFAULT true,
  display_order INT NOT NULL DEFAULT 0
);

COMMENT ON TABLE menu_items IS 'Individual dishes/drinks within a menu category';

CREATE INDEX idx_menu_items_restaurant ON menu_items(restaurant_id);
CREATE INDEX idx_menu_items_category ON menu_items(category_id);

-- ============================================================
-- 6. orders
-- ============================================================
CREATE TABLE orders (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  session_id    UUID NOT NULL REFERENCES table_sessions(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'preparing', 'ready', 'served')),
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE orders IS 'Customer orders placed within a table session';

CREATE INDEX idx_orders_restaurant ON orders(restaurant_id);
CREATE INDEX idx_orders_session ON orders(session_id);
CREATE INDEX idx_orders_status ON orders(status);

-- ============================================================
-- 7. order_items
-- ============================================================
CREATE TABLE order_items (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id     UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  menu_item_id UUID NOT NULL REFERENCES menu_items(id) ON DELETE RESTRICT,
  quantity     INT NOT NULL CHECK (quantity > 0),
  unit_price   NUMERIC NOT NULL CHECK (unit_price >= 0),
  name         TEXT NOT NULL
);

COMMENT ON TABLE order_items IS 'Line items within an order — price and name are snapshots';
COMMENT ON COLUMN order_items.unit_price IS 'Price at time of order (snapshot, not a live reference)';
COMMENT ON COLUMN order_items.name IS 'Item name at time of order (snapshot)';

CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_restaurant ON order_items(restaurant_id);

-- ============================================================
-- 8. waiter_requests
-- ============================================================
CREATE TABLE waiter_requests (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id UUID NOT NULL REFERENCES restaurants(id) ON DELETE CASCADE,
  session_id    UUID NOT NULL REFERENCES table_sessions(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'acknowledged')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE waiter_requests IS 'Customer presses "Call Waiter" button during a session';

CREATE INDEX idx_waiter_requests_restaurant ON waiter_requests(restaurant_id);
CREATE INDEX idx_waiter_requests_session ON waiter_requests(session_id);
